### ISSUE TITLE
Internal error when a slurm prefix is added

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#1]
If an user tries to add slurm prefixes to rpki-valitaion-api through POST request **localhost:8080/rpki-validator-api/slurm/prefix/filter** the following response is given by the rpki-validator-api server

code: 500
message: Internal server error

The following stack trace is displayed in logs file:

_SEVERE: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
mx.nic.lab.rpki.db.exception.ApiDataAccessException: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at mx.nic.lab.rpki.sqlite.impl.TalDAOImpl.getById(TalDAOImpl.java:27)
        at mx.nic.lab.rpki.api.servlet.tal.TalIdServlet.doApiDaRequest(TalIdServlet.java:41)
        at mx.nic.lab.rpki.api.servlet.tal.TalIdServlet.doApiDaRequest(TalIdServlet.java:23)
        at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:73)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:121)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.doGet(ApiServlet.java:212)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)_

The json sent to the server contains the following data:

{"asn":0, "prefix": "10.0.1.0/24", "comment": "Prueba de prefijo no. 0" }

**Comment by TheRedTrainer** [comment]
Verified. According pcarana, this issue was caused because some problems in the way that the rpki-validator daemon was running, locking the bd in some moments. 
When an user tries to execute several requests like adding slurm prefixes, the rpki-validator-api's server doesn't answer an internal error caused by a database lock anymore.
