### ISSUE TITLE
Out of memory sql exception when an user validates a huge prefix

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#13]
If an user tries to validate a huge prefix (such as 1.0.0.0/8 ) for an ASN, the validation took a lot of time until the server logs the following stack trace:

Oct 31, 2018 7:55:10 PM mx.nic.lab.rpki.api.servlet.ApiServlet handleRequest
SEVERE: java.sql.SQLException: Out of memory
mx.nic.lab.rpki.db.exception.ApiDataAccessException: java.sql.SQLException: Out of memory
        at mx.nic.lab.rpki.sqlite.impl.RouteValidationDAOImpl.validate(RouteValidationDAOImpl.java:23)
        at mx.nic.lab.rpki.api.servlet.validate.RouteValidationServlet.doApiDaRequest(RouteValidationServlet.java:78)
        at mx.nic.lab.rpki.api.servlet.validate.RouteValidationServlet.doApiDaRequest(RouteValidationServlet.java:31)
        at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:67)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:130)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.doGet(ApiServlet.java:221)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Out of memory
        at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
        at org.sqlite.core.NativeDB.column_blob(Native Method)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:259)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:266)
        at mx.nic.lab.rpki.sqlite.object.EncodedRpkiObjectDbObject.loadFromDatabase(EncodedRpkiObjectDbObject.java:47)
        at mx.nic.lab.rpki.sqlite.object.EncodedRpkiObjectDbObject.<init>(EncodedRpkiObjectDbObject.java:37)
        at mx.nic.lab.rpki.sqlite.model.RpkiObjectModel.getEncodedByRpkiObjectId(RpkiObjectModel.java:300)
        at mx.nic.lab.rpki.sqlite.model.RpkiObjectModel.loadRelatedObjects(RpkiObjectModel.java:409)
        at mx.nic.lab.rpki.sqlite.model.RpkiObjectModel.getById(RpkiObjectModel.java:106)
        at mx.nic.lab.rpki.sqlite.model.RoaModel.loadRelatedObjects(RoaModel.java:280)

It is necessary to prevent this issue because any user that executes a couple of validation with similar data could affect the server performance/availability

**Comment by pcarana** [comment]
The error was thrown when the API was validating the repositories at the same time that one or multiple requests where made. The problem was at the code logic, when the candidate ROAs were fetched from the database, the whole ROA object was loaded (this included at least 2 more queries to the database per each ROA), so that's a lot of work for the VM.

The problem seems to be solved by filtering the ROAs using the IP family type and load only the basic ROA information of the candidates (which can be covering aggregates or more specific thant the prefix being validated).
