### ISSUE TITLE
ArrayIndexOutOfBoundsException when user tries to add a prefix filter with an invalid prefix length

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#4]
If an user tries to send a POST request to rpki-validator-api server, including a prefix filter that contains an invalid length, the server retrieves an internal error related to an ArrayIndexOutOfBoundsException. 

The url for the POST request is:

**localhost:8080/rpki-validator-api/slurm/prefix/filter**

The json used for the POST request is the following:

**{
   "asn": 123,
   "prefix": "10.0.1.0/244",
   "comment": "TEST TEST"
}**

The stacktrace for the internal error is the following:

_Oct 03, 2018 5:54:22 PM mx.nic.lab.rpki.api.result.error.ErrorResult <init>
SEVERE: 4
java.lang.ArrayIndexOutOfBoundsException: 4
        at mx.nic.lab.rpki.sqlite.object.SlurmPrefixDbObject.validatePrefixValue(SlurmPrefixDbObject.java:317)
        at mx.nic.lab.rpki.sqlite.object.SlurmPrefixDbObject.validate(SlurmPrefixDbObject.java:242)
        at mx.nic.lab.rpki.sqlite.impl.SlurmPrefixDAOImpl.create(SlurmPrefixDAOImpl.java:56)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.handlePost(SlurmPrefixIdServlet.java:179)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.doApiDaRequest(SlurmPrefixIdServlet.java:86)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.doApiDaRequest(SlurmPrefixIdServlet.java:46)
        at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:73)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:121)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.doPost(ApiServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)_

**Comment by pcarana** [comment]
The prefix length validation was made but was also being ignored, so the exception was thrown when the prefix was validated against its prefix length. Now the error of invalid prefix length is returned succesfully by the servlet.

**Comment by TheRedTrainer** [comment]
Verified. If an user tries to post a new prefix filter or a new prefix assertion using a json with an invalid ipv4 prefix length, the rpki-validator-api provide the following json:

{
   "code": 400
   "message": "Multiple errors exist",
   "errors": [
      {
         "title": "SlurmPrefix.prefixLength",
         "description": "Value out of range, it must be between 0 and 32"
      }
   ]
}
