### ISSUE TITLE
Overflow exception when an user tries to create any object with an invalid ASN

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#5]
If an user tries to create any object (prefix filter and assertion, bgpsec filter and assertion) that contains an invalid ASN (for example ASN: 500000000000000000000000000000000000000000000000000000), the rpki-validator-api returns an internal error message json, while the server logs the following stack trace:

_Oct 04, 2018 6:23:43 PM mx.nic.lab.rpki.api.result.error.ErrorResult <init>
SEVERE: Overflow
java.lang.ArithmeticException: Overflow
        at java.math.BigDecimal.longValueExact(BigDecimal.java:3082)
        at org.glassfish.json.JsonNumberImpl.longValueExact(JsonNumberImpl.java:242)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.getSlurmPrefixFromBody(SlurmPrefixIdServlet.java:310)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.handlePost(SlurmPrefixIdServlet.java:176)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.doApiDaRequest(SlurmPrefixIdServlet.java:86)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.doApiDaRequest(SlurmPrefixIdServlet.java:46)
        at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:73)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:121)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.doPost(ApiServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)_

**Comment by pcarana** [comment]
The exception wasn't handled in a proper way, now it's considered to send a more adequate message in the response.

**Comment by TheRedTrainer** [comment]
Verified. If an user tries to create any object using an invalid ASN, the rpki-validator-api server provides the following json:

{
   "code": 400,
   "message": "Invalid ASN, must be a number between 0 and 429967295"
}
