### ISSUE TITLE
Primary key constraint failed exception when an user register multiple prefixes

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#6]
When an user tries to register several prefixes filters and assertions almost concurrently, the server provides the following json containing the primary key constraint failed exception:

_SEVERE: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: slurm_prefix.slp_id)
mx.nic.lab.rpki.db.exception.ApiDataAccessException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: slurm_prefix.slp_id)
        at mx.nic.lab.rpki.sqlite.impl.SlurmPrefixDAOImpl.create(SlurmPrefixDAOImpl.java:66)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.handlePost(SlurmPrefixIdServlet.java:179)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.doApiDaRequest(SlurmPrefixIdServlet.java:86)
        at mx.nic.lab.rpki.api.servlet.slurm.SlurmPrefixIdServlet.doApiDaRequest(SlurmPrefixIdServlet.java:46)
        at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:73)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:121)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.doPost(ApiServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)_

**Comment by pcarana** [comment]
The ID was assigned "manually", so now the DB will assign it to avoid this concurrency error.

The DA (pcarana/rpki-validator-da@f8ba8d1ea5f24129e271d4e4e95fb243752f23a9) and the SQLite Provider (pcarana/rpki-validator-sqlite-prov@c0547d11b3a785431d822e6cd2c7727191f36a19) where modified as well to support this functionality.

**Comment by TheRedTrainer** [comment]
Verified. Even if four simultaneous scripts create 10000 prefix filters, 10000 prefix assertions, 10000 bgpsec filters and 10000 bgpsec assertions, the rpki-validator-api servers is capable of manage all the load without throwing any exception, so the sqlLiteException caused by the primary key constraint failed doesn't happen anymore.
