### ISSUE TITLE
SQLException: out of memory when server is loaded with roa queries

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#8]
If an user sends several roa queries (about 6-8), the size of each answer (around 40,000 rows) affects the server capacity, making the server eventually provide an internal server error including the following stack trace:

SEVERE: java.sql.SQLException: Out of memory
mx.nic.lab.rpki.db.exception.ApiDataAccessException: java.sql.SQLException: Out of memory
        at mx.nic.lab.rpki.sqlite.impl.RoaDAOImpl.getAll(RoaDAOImpl.java:34)
        at mx.nic.lab.rpki.api.servlet.roa.RoaListServlet.doApiDaRequest(RoaListServlet.java:51)
        at mx.nic.lab.rpki.api.servlet.roa.RoaListServlet.doApiDaRequest(RoaListServlet.java:25)
        at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:73)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:121)
        at mx.nic.lab.rpki.api.servlet.ApiServlet.doGet(ApiServlet.java:212)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Out of memory
        at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
        at org.sqlite.core.NativeDB.column_blob(Native Method)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:259)
        at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:266)
        at mx.nic.lab.rpki.sqlite.object.EncodedRpkiObjectDbObject.loadFromDatabase(EncodedRpkiObjectDbObject.java:47)
        at mx.nic.lab.rpki.sqlite.object.EncodedRpkiObjectDbObject.<init>(EncodedRpkiObjectDbObject.java:37)
        at mx.nic.lab.rpki.sqlite.model.RpkiObjectModel.getEncodedByRpkiObjectId(RpkiObjectModel.java:300)
        at mx.nic.lab.rpki.sqlite.model.RpkiObjectModel.loadRelatedObjects(RpkiObjectModel.java:409)
        at mx.nic.lab.rpki.sqlite.model.RpkiObjectModel.getById(RpkiObjectModel.java:106)
        at mx.nic.lab.rpki.sqlite.model.RoaModel.loadRelatedObjects(RoaModel.java:277)
        at mx.nic.lab.rpki.sqlite.model.RoaModel.getAll(RoaModel.java:109)
        at mx.nic.lab.rpki.sqlite.impl.RoaDAOImpl.getAll(RoaDAOImpl.java:32)
        ... 29 more

**Comment by pcarana** [comment]
To avoid this issue, a default limit was set to the results returned by the server. This is set by a configuration property named `max.response.results` with a default value of **5000**.

Also, the response of the servlets that return a list of objects was modified to indicate the total results found, the results returned (number and objects), as well as the page parameters used (limit and offset). The response has the following format:
```
{
  results: [JSON Array - list of found results],
  found: [integer - number of total results found],
  returned: [integer - number of results returned after the paging is applied],
  page: {
    limit: [integer - paging limit applied to the search],
    offset: [integer - paging offset applied to the search]
  }
}
```
The affected servlets are (all of them using the **GET** method):
* `/tal`
* `/roa`
* `/slurm/prefix`
* `/slurm/prefix/filter`
* `/slurm/prefix/assertion`
* `/slurm/bgpsec`
* `/slurm/bgpsec/filter`
* `/slurm/bgpsec/assertion`

**Comment by TheRedTrainer** [comment]
Reopen. Despite the fact that the new max response results configuration avoid an issue with the server and db capacity, if an user tries to configure a non positive integer value (such as 0 or a negative value), the server assume a query without any limit , even ignoring a limit parameter passed through the query itself.

It is necessary to define and restrict the expected values for this parameter and define how the user could tell the server that it requires no limit for queries.

**Comment by pcarana** [comment]
Now the behaviour is standard to avoid misinterpretations at the server:
* The configuration property `max.response.results` allows only positive integer values or zero, where 0 means 'no limit'.
* If the client sends a value greater than the configured `max.response.results`, then return the number of results limited by the server (considering that 0 means 'no limit'), otherwise return the number of results requested by the client.
  * eg. If the server has configured `max.response.results = 0` and the request `/roa?limit=10` is made, then only **10 results** will be returned (since a limit of 10 is lesser than 'no limit').
* The JSON object at the response to lists requests will have the `page` property only if the results are limited, in another words, when the limit is greater than 0.
  * eg. If the server has configured `max.response.results = 0` and the request `/roa` is made, then the response will have the following format (note that the property `page` isn't present):

  ```
  {
    results: [JSON Array - list of found results],
    found: [integer - number of total results found],
    returned: [integer - number of results returned, equal to the 'found' property],
  }
  ```

**Comment by TheRedTrainer** [comment]
Verified. If the admin tries to configure a negative value for max.response.results property, the server logs a stack trace telling that it is an invalid value. If the admin configures a zero value for this property, the server doesn't define a limite for query results. If the admin configures a positive integer value, the server will only return the amount of results defined as a max result set size, no matter if the user defines a greater limit within the query parameters (for example, "?limit=10000" when the max.response.results value is 100).
