### ISSUE TITLE
SQLiteException: Database file is locked when roa query is executed while rpki validator daemon is running

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#9]
If an user executes the rpki-validator-api/roa querie multiple times and any of these queries collide with the rpki validator daemon execution, the query hangs and server doesn't respond. The following stack trace is registered in the app log:

Oct 22, 2018 1:50:30 PM mx.nic.lab.rpki.api.validation.TrustAnchorValidationService loadAndValidateTals
SEVERE: Error persisting validation run mx.nic.lab.rpki.db.pojo.ValidationRun[id=19, updatedAt=null, completedAt=null, status=RUNNING, type=TRUST_ANCHOR, talId=5, talCertificateURI=null, rpkiRepositories=[], validationChecks=[]]
mx.nic.lab.rpki.db.exception.ApiDataAccessException: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at mx.nic.lab.rpki.sqlite.impl.ValidationRunDAOImpl.create(ValidationRunDAOImpl.java:28)
        at mx.nic.lab.rpki.api.validation.TrustAnchorValidationService.loadAndValidateTals(TrustAnchorValidationService.java:122)
        at mx.nic.lab.rpki.api.validation.TrustAnchorValidationService.validate(TrustAnchorValidationService.java:73)
        at mx.nic.lab.rpki.api.validation.QuartzTrustAnchorValidationJob.execute(QuartzTrustAnchorValidationJob.java:45)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:909)
        at org.sqlite.core.DB.newSQLException(DB.java:921)
        at org.sqlite.core.DB.throwex(DB.java:886)
        at org.sqlite.core.DB.exec(DB.java:155)
        at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
        at mx.nic.lab.rpki.sqlite.model.ValidationRunModel.create(ValidationRunModel.java:159)
        at mx.nic.lab.rpki.sqlite.impl.ValidationRunDAOImpl.create(ValidationRunDAOImpl.java:26)
        ... 5 more

**Comment by pcarana** [comment]
Please check if the fix https://github.com/pcarana/rpki-validator-api/issues/8#issuecomment-433198821 avoids this exception as well.

**Comment by TheRedTrainer** [comment]
Verified. This situation could be unavoidable because the amount of resources and validations that the daemon processes every X minutes increase the possibility to lock the database, and this situation could be worse every year when more asn and roas are registered for rpki. The best way to avoid this issue is defining a default limit for any query in order to avoid an overload for queries that contain a huge result set greater thatn expected. This limit is defined on fix #8
